version: '3.3'
services:
  spp-platform:
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
      - "5450:5450"
      - "5455:5455"
    build:
      context: .
      dockerfile: Dockerfile-spp-platform-debian
    depends_on:
      - redis
    links:
      - redis
    environment:
      - SPP_SYSTEM_ACCESS_TOKEN=change-me
  redis:
    image: redis:6.2.1
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  skywalking-oap:
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "11800:11800"
      - "12800:12800"
      #- "5106:5106"
    build:
      context: .
      dockerfile: Dockerfile-skywalking-oap
#    environment:
#      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5106
  spp-example-webapp:
    container_name: spp-example-webapp
    hostname: spp-example-webapp
#    ports:
#      - "5105:5105"
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    build:
      context: .
      dockerfile: Dockerfile-spp-example-webapp
#  skywalking-ui:
#    image: apache/skywalking-ui:8.6.0
#    container_name: skywalking-ui
#    hostname: skywalking-ui
#    ports:
#      - "8888:8080"
#    depends_on:
#      - skywalking-oap
#    links:
#      - skywalking-oap
#    environment:
#      - SW_OAP_ADDRESS=skywalking-oap:12800