name: Update demo.sourceplus.plus

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.svg'
  workflow_dispatch:

jobs:
  update-demo:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Redeploy demo.sourceplus.plus
        uses: appleboy/ssh-action@master
        with:
          host: demo.sourceplus.plus
          username: root
          key: ${{ secrets.DEMO_SSH_KEY }}
          script_stop: true

          #todo: redeploy demo with no downtime
          script: |
            cd /opt/dev/private/demo
            docker-compose down
            docker image prune -f --all
            docker-compose up --force-recreate --build -d
            docker image prune -f
